include: package:lints/recommended.yaml

# Uncomment the following section to specify additional rules.

analyzer:
  exclude:
    - lib/src/gdextension_bindings.dart
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    native_function_body_in_non_sdk_code: ignore
