name: godot_dart
description: Dart bindings for the Godot game engine
version: 1.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  ffi: ^2.0.1
  meta: ^1.9.0
  path: ^1.8.3
  collection: ^1.7.1

dev_dependencies:
  ffigen: ^7.2.4
  lints: ^2.0.0

ffigen:
  output: 'lib/src/core/gdextension_ffi_bindings.dart'
  name: GDExtensionFFI
  headers:
    entry-points:
      - '../../godot-headers/godot/gdextension_interface.h'