include: package:lints/recommended.yaml

analyzer:
  exclude:
    - lib/src/godot_extension_api_json.dart
  language:
    strict-casts: true
    strict-raw-types: true
  
linter:
  rules:
    - prefer_single_quotes
    - camel_case_types
    - prefer_relative_imports
    - unawaited_futures
