include: package:lints/recommended.yaml

analyzer:
  strong-mode:
    implicit-dynamic: false
  
linter:
  rules:
    - prefer_single_quotes
    - camel_case_types
    - prefer_relative_imports
    - unawaited_futures
