name: binding_generator
description: Tool to generate Dart for Godot from the extensions_api.json file
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
dependencies:
  mustache_template: ^2.0.0
  path: ^1.8.3
