include: package:lints/recommended.yaml

# Uncomment the following section to specify additional rules.

analyzer:
  exclude:
    - lib/src/core/gdextension_ffi_bindings.dart
  language:
    strict-casts: true
    strict-raw-types: true
  
  errors:
    native_function_body_in_non_sdk_code: ignore

linter:
  rules:
    prefer_single_quotes: true
    prefer_relative_imports: true
    unawaited_futures: true