name: godot_dart
description: Dart bindings for the Godot game engine
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  ffi: ^2.0.1
  meta: ^1.9.0
  path: ^1.8.3
  collection: ^1.7.1  

dev_dependencies:
  ffigen: ^11.0.0
  lints: ^2.0.0
  
ffigen:
  output: 'lib/src/core/gdextension_ffi_bindings.dart'
  name: GDExtensionFFI
  headers:
    entry-points:
      - '../../cpp/gde_c_interface.h'
  compiler-opts:
      - '-I../../../godot-cpp/gdextension/'