name: fetch_dart
description: Fetch the most recent version of dart_shared_library either from github or locally
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.4.2
  path: ^1.9.0
  logging: ^1.2.0
  github: ^9.24.0
  http: ^1.2.2
  archive: ^3.6.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
