name: godot_dart_build
description: build_runner interface for simplifying binding to Godot
version: 1.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  analyzer: ^5.13.0
  meta: ^1.9.0
  path: ^1.8.3
  collection: ^1.7.1
  build: ^2.0.0
  build_config: ^1.1.1
  source_gen: ^1.3.2
  godot_dart:
    path: '../godot_dart'

dev_dependencies:
  ffigen: ^7.2.4
  lints: ^2.0.0