name: godot_dart_example
description: An example of using Dart in Godot
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  ffi: ^2.0.1
  godot_dart:
    path: ../../src/dart

dev_dependencies:
  lints: ^2.0.0
